import { setAlgoliaInfo } from './doc';
// This is the main JS file for all Algolia related logic. 
// InstantSearch is used, documentation root: https://www.algolia.com/doc/guides/building-search-ui/getting-started/js/
// This project was generated by the 'npx create-instantsearch-app' command as it appears on the configuration and modified later
export function init_algolia(appId, searchKey, indexName) {
    const { algoliasearch, instantsearch } = window;
    // Initialize the Algolia Search client and connect to our index
    const searchClient = algoliasearch(appId, searchKey);
    window.searchClient = searchClient;
    window.searchIndexName = indexName;
    const search = instantsearch({
        indexName: indexName,
        routing: true,
        searchClient,
    });
    // If Algolia runs into an error, it's most likely an issue with AppId/SearchKey/IndexName. Redirect back to setup
    search.addListener('error', function () { 
        showSetup('Algolia failed to initialize, parameters are not configured correctly.')
    })
    


    // The main logic for Algolia initialization, this initializes all the widgets we use
    search.addWidgets([
        instantsearch.widgets.searchBox({
            container: '#searchbox',
            placeholder: 'Search for any keyword',
            autofocus: true,
            searchAsYouType: true,
            showReset: true,
            showLoadingIndicator: true
        }),
        instantsearch.widgets.hitsPerPage({
            container: '#hitsPerPage',
            items: [
                { label: '10 hits per page', value: 10, default: true },
                { label: '20 hits per page', value: 20 },
                { label: '50 hits per page', value: 50 },
                { label: '100 hits per page', value: 100 },
            ]
        }),
        instantsearch.widgets.pagination({
            container: '#paginator',
            showFirst: true,
            showLast: true,
            showPrevious: true,
            showNext: true,
        }),
        instantsearch.widgets.refinementList({
            container: '#language',
            attribute: 'language'
        }),
        instantsearch.widgets.refinementList({
            container: '#topics',
            attribute: 'topics'
        }),
        instantsearch.widgets.rangeSlider({
            container: '#forks',
            attribute: 'forks',
            precision: 10
        }),
        instantsearch.widgets.hits({
            container: '#hits',
            templates: {
                item: `
                    <article id="hit-{{objectID}}">
                        <div class="title">
                            <h2>{{#helpers.highlight}}{ "attribute": "name" }{{/helpers.highlight}}</h2>
                            <span class="info stars" title="Watchers">
                                <svg aria-hidden="true"> 
                                <path d="M12 .288l2.833 8.718h9.167l-7.417 5.389 2.833 8.718-7.416-5.388-7.417 5.388 2.833-8.718-7.416-5.389h9.167z"></path>
                                </svg>
                                <span>{{watchers}}</span>
                            </span>
                            <span class="info" title="Forks">
                                <svg style="width:24px;height:24px" viewBox="0 0 24 24">
                                    <path fill="currentColor" d="M6,2A3,3 0 0,1 9,5C9,6.28 8.19,7.38 7.06,7.81C7.15,8.27 7.39,8.83 8,9.63C9,10.92 11,12.83 12,14.17C13,12.83 15,10.92 16,9.63C16.61,8.83 16.85,8.27 16.94,7.81C15.81,7.38 15,6.28 15,5A3,3 0 0,1 18,2A3,3 0 0,1 21,5C21,6.32 20.14,7.45 18.95,7.85C18.87,8.37 18.64,9 18,9.83C17,11.17 15,13.08 14,14.38C13.39,15.17 13.15,15.73 13.06,16.19C14.19,16.62 15,17.72 15,19A3,3 0 0,1 12,22A3,3 0 0,1 9,19C9,17.72 9.81,16.62 10.94,16.19C10.85,15.73 10.61,15.17 10,14.38C9,13.08 7,11.17 6,9.83C5.36,9 5.13,8.37 5.05,7.85C3.86,7.45 3,6.32 3,5A3,3 0 0,1 6,2M6,4A1,1 0 0,0 5,5A1,1 0 0,0 6,6A1,1 0 0,0 7,5A1,1 0 0,0 6,4M18,4A1,1 0 0,0 17,5A1,1 0 0,0 18,6A1,1 0 0,0 19,5A1,1 0 0,0 18,4M12,18A1,1 0 0,0 11,19A1,1 0 0,0 12,20A1,1 0 0,0 13,19A1,1 0 0,0 12,18Z" />
                                </svg>
                                <span>{{forks}}</span>
                        </span>
                        </div>
                        <div class="desc">{{#helpers.highlight}}{ "attribute": "description" }{{/helpers.highlight}}</div>
                        <div class="properties">
                            
                            <div class="prop">
                                <div class="name">Owner:</div>
                                <a class="value" target="_blank" href="{{ownerUrl}}">{{#helpers.highlight}}{ "attribute": "ownerLogin" }{{/helpers.highlight}}</a>
                            </div>
                            {{#url}}
                            <div class="prop">
                                <div class="name">URL:</div>
                                <a class="value" target="_blank" href="{{url}}">{{#helpers.highlight}}{ "attribute": "url" }{{/helpers.highlight}}</a>
                            </div>
                            {{/url}}
                            {{#homePage}}
                            <div class="prop">
                                <div class="name">Home page:</div>
                                <a class="value" target="_blank" href="{{homePage}}">{{#helpers.highlight}}{ "attribute": "homePage" }{{/helpers.highlight}}</a>
                            </div>
                            {{/homePage}}
                            {{#language}}
                            <div class="prop">
                                <div class="name">Language:</div>
                                <div class="value">{{#helpers.highlight}}{ "attribute": "language" }{{/helpers.highlight}}</div>
                            </div>
                            {{/language}}
                            {{#topicsList}}
                            <div class="prop">
                                <div class="name">Topics:</div>
                                <div class="value">{{#helpers.highlight}}{ "attribute": "topicsList" }{{/helpers.highlight}}</div>
                            </div>
                            {{/topicsList}}
                        </div>
                        <button onclick="openDoc('{{objectID}}',{{totalCount}},'{{name}}')">Open documentation</button>
                    </article>
`
            }
        })

    ]);


    search.start();

}
